In [6]:
import sys
!conda install --yes --prefix {sys.prefix} openpyxl

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\ericwgreene\anaconda3\envs\jupyter_labs_conda

  added / updated specs:
    - openpyxl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    et_xmlfile-1.1.0           |   py39haa95532_0          10 KB
    ------------------------------------------------------------
                                           Total:          10 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         pkgs/main/win-64::et_xmlfile-1.1.0-py39haa95532_0
  jdcal              pkgs/main/noarch::jdcal-1.4.1-py_0
  openpyxl           pkgs/main/noarch::openpyxl-3.0.7-pyhd3eb1b0_0



Downloading and Extracting Packages

et_xmlfile-1.1.0     | 10 KB     |            |   0%
et_xmlfile-1.1.0     | 10 KB     | ########## | 100%
et_xmlfile-1.1.0     | 10 KB     | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

In [14]:
import pathlib

import pandas as pd
import numpy as np

In [11]:
wine_data_file_name = pathlib.Path("data", "Portuguese_VinhoVerde_RedWine_Quality.xlsx")

In [11]:
wine_data = pd.read_excel(wine_data_file_name, "data")

wine_data

In [11]:
wine_column_descriptions = pd.read_excel(wine_data_file_name, "column-descriptions")

wine_column_descriptions

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,11.6,0.580,0.66,2.20,0.074,10.0,47.0,1.00080,3.25,0.57,9.0,3
1,10.4,0.610,0.49,2.10,0.200,5.0,16.0,0.99940,3.16,0.63,8.4,3
2,7.4,1.185,0.00,4.25,0.097,5.0,14.0,0.99660,3.63,0.54,10.7,3
3,10.4,0.440,0.42,1.50,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3
4,8.3,1.020,0.02,3.40,0.084,6.0,11.0,0.99892,3.48,0.49,11.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,8.6,0.420,0.39,1.80,0.068,6.0,12.0,0.99516,3.35,0.69,11.7,8
1595,5.5,0.490,0.03,1.80,0.044,28.0,87.0,0.99080,3.50,0.82,14.0,8
1596,7.2,0.330,0.33,1.70,0.061,3.0,13.0,0.99600,3.23,1.10,10.0,8
1597,7.2,0.380,0.31,2.00,0.056,15.0,29.0,0.99472,3.23,0.76,11.3,8
1598,7.4,0.360,0.30,1.80,0.074,17.0,24.0,0.99419,3.24,0.70,11.4,8

In [13]:
wine_data.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [17]:
wine_dtypes = {
    "fixed acidity": np.float32,
    "volatile acidity": np.float32,
    "citric acid": np.float32,
    "residual sugar": np.float32,
    "chlorides": np.float32,
    "free sulfur dioxide": np.int8,
    "total sulfur dioxide": np.int8,
    "density": np.float32,
    "pH": np.float32,
    "sulphates": np.float32,
    "alcohol": np.float32,
    "quality": np.int8,
}


wine_data = pd.read_excel(wine_data_file_name, "data", dtype=wine_dtypes)

wine_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,11.6,0.580,0.66,2.20,0.074,10,47,1.00080,3.25,0.57,9.0,3
1,10.4,0.610,0.49,2.10,0.200,5,16,0.99940,3.16,0.63,8.4,3
2,7.4,1.185,0.00,4.25,0.097,5,14,0.99660,3.63,0.54,10.7,3
3,10.4,0.440,0.42,1.50,0.145,34,48,0.99832,3.38,0.86,9.9,3
4,8.3,1.020,0.02,3.40,0.084,6,11,0.99892,3.48,0.49,11.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,8.6,0.420,0.39,1.80,0.068,6,12,0.99516,3.35,0.69,11.7,8
1595,5.5,0.490,0.03,1.80,0.044,28,87,0.99080,3.50,0.82,14.0,8
1596,7.2,0.330,0.33,1.70,0.061,3,13,0.99600,3.23,1.10,10.0,8
1597,7.2,0.380,0.31,2.00,0.056,15,29,0.99472,3.23,0.76,11.3,8
1598,7.4,0.360,0.30,1.80,0.074,17,24,0.99419,3.24,0.70,11.4,8